name: Deploy AI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Build do projeto com Maven (na raiz, pois o pom.xml está aqui)
      - name: Build with Maven
        run: mvn -B clean install

      # 4. Login no Docker Hub (usando o token definido no secret DOCKERHUB_TOKEN)
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: "mateus1711"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Build e push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mateus1711/deploy_ai-ci:${{ github.sha }}

      # 7. Deploy via SSH na AWS
      - name: Deploy via SSH na AWS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_TEST }}      # IP público da sua VM
          username: "ubuntu"                  # Usuário SSH (geralmente "ubuntu")
          key: ${{ secrets.KEY_TEST }}        # Conteúdo da sua chave .pem
          port: 22
          script: |
            docker rm -f deploy_AI || true
            docker run -d -p 18.230.226.30:8080 --name deploy_AI --network=rede-entidade mateus1711/deploy_ai-ci:${{ github.sha }}
